AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/*.rb'
    - 'bin/**/*'
  
Style/Encoding:
  EnforcedStyle: always
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  
# Offense count: 127
Metrics/AbcSize:
  Max: 21

# Offense count: 31
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 158

# Offense count: 56
Metrics/CyclomaticComplexity:
  Max: 8

# Offense count: 191
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 16

# Offense count: 11
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 156

# Offense count: 29
Metrics/PerceivedComplexity:
  Max: 8
