AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/*.rb'
    - 'bin/**/*'

  DisplayCopNames: true
  StyleGuideCopsOnly: false

Style/Documentation:
  Exclude:
    - 'lib/**/version.rb'

Metrics/LineLength:
  Max:  100

Metrics/MethodLength:
  Max:  15

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 158


